---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: unInstall apache2 package
    apt:
      name: apache2
      state: absent 

  - name: unInstall php support package
    apt:
      name:  libapache2-mod-php
      state: absent
