---

- hosts: all
  become: true
  pre_tasks:
 
  - name: updates repo cache Ubuntu
    tags: always  
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: updates repo cache Rocky servers
    tags: always  
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Rocky"


- hosts: all
  become: true
  tasks:
#a place holder for doing ssh key management.     
  - name: add ssh key for new user
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGrbYppJ9pW6hYN6w9fJ4bC+0A5im66k00a4cth53BqB ansible"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Rocky servers
    tags: apache,httpd,rocky
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: start httpd (Rocky)
    tags: apache,rocky,apache2
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky" 

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb
    tags: mariadb,db,rocky
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install mariadb ubuntu
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
   
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
    tags: workstations
    package:
      name: unzip
      
  - name: Install Terraform
    tags: workstations
    unarchive: 
      src: https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755

